/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Student_DatabaseSQL;

import javax.swing.*;
import java.io.*;
import java.util.*;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.awt.Color;

/**
 *
 * @author N-vision
 */
public class Student_Info extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Student_Info.class.getName());

    /**
     * Creates new form Student_Info
     */
    public Student_Info() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        Panel1 = new javax.swing.JPanel();
        studentId = new javax.swing.JLabel();
        studentIdTxt = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        age = new javax.swing.JLabel();
        ageTxt = new javax.swing.JTextField();
        gradeTxt = new javax.swing.JTextField();
        grade = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        search = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        delete = new javax.swing.JLabel();
        deleteTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        StudentTable = new javax.swing.JTable();
        searchBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentId.setText("Student ID");
        Panel1.add(studentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 21, -1, -1));
        Panel1.add(studentIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 229, -1));

        name.setText("Name");
        Panel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 40, 40));
        Panel1.add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 229, -1));

        age.setText("Age");
        Panel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 40, 30));

        ageTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTxtActionPerformed(evt);
            }
        });
        Panel1.add(ageTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 229, -1));
        Panel1.add(gradeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 229, -1));

        grade.setText("Grade");
        Panel1.add(grade, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 105, 40, 30));

        addBtn.setText("add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        Panel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 70, -1));

        clearBtn.setText("clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        Panel1.add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 70, -1));

        search.setText("Search");
        Panel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, 20));
        Panel1.add(searchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 150, -1));

        delete.setText("Delete ID");
        Panel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, 20));

        deleteTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTxtActionPerformed(evt);
            }
        });
        Panel1.add(deleteTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 150, -1));

        StudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Age", "Grade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(StudentTable);
        if (StudentTable.getColumnModel().getColumnCount() > 0) {
            StudentTable.getColumnModel().getColumn(0).setResizable(false);
            StudentTable.getColumnModel().getColumn(1).setResizable(false);
            StudentTable.getColumnModel().getColumn(2).setResizable(false);
            StudentTable.getColumnModel().getColumn(3).setResizable(false);
        }

        Panel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 320, 140));

        searchBtn.setText("search");
        searchBtn.setHideActionText(true);
        searchBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        Panel1.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 70, -1));

        deleteBtn.setText("delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        Panel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ageTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTxtActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        
         // Clear all input text fields
    studentIdTxt.setText("");
    nameTxt.setText("");
    ageTxt.setText("");
    gradeTxt.setText("");
    
    // Optional: clear search and delete fields
    searchTxt.setText("Student ID or Name");
    deleteTxt.setText("ex. 1234-1234");
    
    // Optional: clear table contents
    DefaultTableModel model = (DefaultTableModel) StudentTable.getModel();
    model.setRowCount(0);
    
    // Optionally reload all students from database after clearing table
    loadStudentsFromDatabase(); 
    }//GEN-LAST:event_clearBtnActionPerformed

    private void deleteTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteTxtActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        
                                                       
    String keyword = searchTxt.getText().trim();

    if (keyword.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter Student ID or Name to search.");
        return;
    }

    DefaultTableModel model = (DefaultTableModel) StudentTable.getModel();
    model.setRowCount(0); // Clear table first

    try {
    Connection con = DBconnect.connect();
    String sql = "SELECT student_id, name, age, grade FROM student_sql WHERE student_id LIKE ? OR name LIKE ?";
    PreparedStatement pst = con.prepareStatement(sql);
    
    pst.setString(1, "%" + keyword + "%");
    pst.setString(2, "%" + keyword + "%");

    java.sql.ResultSet rs = pst.executeQuery();

    boolean found = false;
    while (rs.next()) {
        found = true;
        Object[] row = {
            rs.getString("student_id"),
            rs.getString("name"),
            rs.getInt("age"),
            rs.getString("grade")
        };
        model.addRow(row);
    }

    if (!found) {
        JOptionPane.showMessageDialog(this, "No matching student found!");
    }

    rs.close();
    pst.close();
    con.close();

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Search Error: " + e.getMessage());
}

    }//GEN-LAST:event_searchBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
         String id = studentIdTxt.getText().trim();
        String name = nameTxt.getText().trim();
        String age = ageTxt.getText().trim();
        String grade = gradeTxt.getText().trim();

        // 2. Check for empty fields
        if (id.isEmpty() || name.isEmpty() || age.isEmpty() || grade.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Fill out the form");
            return;
        }

        // 3. Convert age to integer only
        int ageInt;
        try {
            ageInt = Integer.parseInt(age);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Age must be a number");
            return;
        }

        // 4. Add to JTable
        DefaultTableModel model = (DefaultTableModel) StudentTable.getModel();
        model.insertRow(0, new Object[]{id, name, ageInt, grade}); // ID as string

        // 5. Clear input fields
        studentIdTxt.setText("");
        nameTxt.setText("");
        ageTxt.setText("");
        gradeTxt.setText("");

        // 6. Save to MySQL database
        try {
            Connection con = DBconnect.connect();
            String sql = "INSERT INTO student_sql (student_id, name, age, grade) VALUES (?, ?, ?, ?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, id);      // ID is string now
            pst.setString(2, name);
            pst.setInt(3, ageInt);
            pst.setString(4, grade);

            pst.executeUpdate();
            con.close();

            JOptionPane.showMessageDialog(this, "Student added to database successfully!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error saving to database: " + e.getMessage());
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        
         String idToDelete = deleteTxt.getText().trim();

    if (idToDelete.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter Student ID to delete.");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this, 
        "Are you sure you want to delete student with ID " + idToDelete + "?",
        "Confirm Delete", JOptionPane.YES_NO_OPTION);

    if (confirm != JOptionPane.YES_OPTION) {
        return; // user cancelled
    }

    try {
        Connection con = DBconnect.connect();
        String sql = "SELECT student_id, name, age, grade FROM student_sql";

        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, idToDelete);

        int rowsDeleted = pst.executeUpdate();
        con.close();

        if (rowsDeleted > 0) {
            JOptionPane.showMessageDialog(this, "Student deleted successfully!");
            loadStudentsFromDatabase(); // refresh table
        } else {
            JOptionPane.showMessageDialog(this, "No student found with that ID.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error deleting: " + e.getMessage());
    }
    }//GEN-LAST:event_deleteBtnActionPerformed

    
    private void loadStudentsFromDatabase() {
        DefaultTableModel model = (DefaultTableModel) StudentTable.getModel();
        model.setRowCount(0); // clear table

            try {
                Connection con = DBconnect.connect();
                if (con != null) {
                    String sql = "SELECT student_id, name, age, grade FROM student_sql";
                    PreparedStatement pst = con.prepareStatement(sql);
                    java.sql.ResultSet rs = pst.executeQuery();

                    while (rs.next()) {
                        Object[] row = {
                            rs.getString("student_id"),
                            rs.getString("name"),
                            rs.getInt("age"),
                            rs.getString("grade")
                        };
                        model.addRow(row);
                    }
                    con.close();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error loading students: " + e.getMessage());
            }
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Student_Info().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private javax.swing.JTable StudentTable;
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel age;
    private javax.swing.JTextField ageTxt;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel delete;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField deleteTxt;
    private javax.swing.JLabel grade;
    private javax.swing.JTextField gradeTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JLabel search;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JLabel studentId;
    private javax.swing.JTextField studentIdTxt;
    // End of variables declaration//GEN-END:variables
}
